---
# These tasks sets up bash with bash-it

- file: path="/home/{{ user }}/.bash_it" state=absent

- name: Clone bashit
  shell: >
    . "/home/{{ user }}/.bashrc" &&
    { [[ -d "/home/{{ user }}/.bash_it" ]] && rm -rf "/home/{{ user }}/.bash_it" || echo "Nothing to delete for bash-it"; } &&
    git clone --depth=1 https://github.com/Bash-it/bash-it.git "/home/{{ user }}/.bash_it"
  args:
    executable: /bin/bash
  register: bashit_cloned

- name: Install bashit
  shell: >
    . "/home/{{ user }}/.bashrc" &&
    echo y > $TMPDIR/bash-it-install-option &&
    /bin/bash "/home/{{ user }}/.bash_it/install.sh" < $TMPDIR/bash-it-install-option &&
    rm $TMPDIR/bash-it-install-option
  args:
    executable: /bin/bash
  register: bashit_installed
  when: bashit_cloned|success and bashrc_backedup|success

- name: Add composure
  shell: >
    . "/home/{{ user }}/.bashrc" &&
    cd "/home/{{ user }}/.bash_it/custom" &&
    curl -L http://git.io/composure > composure.sh &&
    chmod +x composure.sh
  args:
    executable: /bin/bash
  when: bashit_installed|success

- name: Add placeholder for custom aliases
  copy: src=aliases.bash
    dest="/home/{{ user }}/.bash_it/custom/aliases.bash"
    owner={{ user }}
    group={{ user }}
    mode=662
  when: bashit_installed|success
