# If running interactively, always load the home dir first
case $- in
    *i*)
        if [[ ! -z $TMUX ]]; then
          pwd
        else
          cd $HOME
        fi
        ;;
      *) ;;
esac
command -v dircolors >/dev/null 2>&1 && test -r $HOME/.dircolors && eval "$(dircolors -b $HOME/.dircolors)" || eval "$(dircolors -b)"
[[ -f /etc/bashrc ]] && . /etc/bashrc
[[ -f /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion || . /etc/bash_completion
