---
# These tasks set up some common binaries needed to work with

- name: Get rid of dot local cause it messes python2.7 up in ubuntu
  shell: test -d "/home/{{ user }}/.local" && rm -rf "/home/{{ user }}/.local"
  args:
    executable: /bin/bash
  ignore_errors: yes

- file: state=directory
    dest="/home/{{ user }}/bin"
    owner={{ user }}
    group={{ user }}

- file: state=directory
    dest="/home/{{ user }}/tmp"
    owner={{ user }}
    group={{ user }}

- file: state=directory
    dest="/home/{{ user }}/share"
    owner={{ user }}
    group={{ user }}

- name: Add bashrc
  copy: src=bashrc
    dest="/home/{{ user }}/.bashrc"
    owner={{ user }}
    group={{ user }}
    mode=644
  register: custom_bashrc_added

- name: Add utilities to your shell
  copy: src=bash_utils.sh
    dest="/home/{{ user }}/.bash_utils.sh"
    owner={{ user }}
    group={{ user }}
    mode=775
  register: custom_bash_utils_added

- name: Update bashrc to source the custom bash util fns
  shell: echo '[[ -f $HOME/.bash_utils.sh ]] && . $HOME/.bash_utils.sh' >> "/home/{{ user }}/.bashrc"
  when: custom_bashrc_added|success and custom_bash_utils_added | success

- name: Add activate_profile file to your home dir
  copy: src=activate_profile.sh
    dest="/home/{{ user }}/.activate_profile.sh"
    owner={{ user }}
    group={{ user }}
  register: activate_profile_script_added

- name: Add env_vars file to your home dir
  copy: src=env_vars.sh
    dest="/home/{{ user }}/.env_vars.sh"
    owner={{ user }}
    group={{ user }}
  register: custom_env_vars_added
  when: activate_profile_script_added|success

- name: Add extra line to profile file
  shell: echo '[[ -f $HOME/.env_vars.sh ]] && . $HOME/.env_vars.sh' >> "/home/{{ user }}/.bashrc"
  when: custom_bashrc_added|success and custom_env_vars_added|success

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: no
  with_items:
    - curl
    - git
    - wget
    - git-extras
    - gitk # Cant really use it if there is no GUI
    - unzip
    - libffi-dev
    - libpq-dev
    - libsqlite3-dev
    - libssl-dev
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - libexpat-dev
    - zlib1g-dev
    - python-dev
    - python3-dev
    - ruby-dev
    - nodejs-dev
    - gettext
    - libyaml-dev
    - libreadline-dev
    - linux-libc-dev
    - libjpeg-dev
    - libfreetype6
    - libfreetype6-dev
    - build-essential
    - sqlite
    - tcl
    - xclip
    - m4
    - gcc
    - cmake
    - scons
    - autoconf
    - automake
    - autoconf-archive
    - libtool
    - patch
    - openssl
    - flex
    - bison
    - python-pip
    - python
    - perl
    - ruby
    - nodejs
    - golang
    - default-jdk
    - lua5.1
    - luajit
    - binutils
    - coreutils
    - moreutils
    - npm
    - tmux
    - dconf-cli
  become: true
  become_user: root

- name: Install version managers for langs
  shell: >
    { [[ ! -d "/home/{{ user }}/.pyenv" ]] && (git clone https://github.com/pyenv/pyenv.git "/home/{{ user }}/.pyenv" && git clone https://github.com/pyenv/pyenv-virtualenv.git "/home/{{ user }}/.pyenv/plugins/pyenv-virtualenv" && git clone https://github.com/pyenv/pyenv-virtualenvwrapper.git "/home/{{ user }}/.pyenv/plugins/pyenv-virtualenvwrapper"); } || echo 'pyenv already installed'; \
    { [[ ! -d "/home/{{ user }}/.rbenv" ]] && (git clone https://github.com/rbenv/rbenv.git "/home/{{ user }}/.rbenv" && git clone https://github.com/rbenv/ruby-build.git "/home/{{ user }}/.rbenv/plugins/ruby-build"); } || echo 'pyenv already installed'; \
    { [[ ! -d "/home/{{ user }}/.nvm" ]] && (git clone https://github.com/creationix/nvm.git "/home/{{ user }}/.nvm"); } || echo 'pyenv already installed'; \
    { [[ ! -d "/home/{{ user }}/.jenv" ]] && (git clone https://github.com/gcuisinier/jenv.git "/home/{{ user }}/.jenv"); } || echo 'pyenv already installed'; \
    { [[ ! -d "/home/{{ user }}/.goenv" ]] && (git clone https://github.com/syndbg/goenv.git "/home/{{ user }}/.goenv"); } || echo 'pyenv already installed'; \
    { [[ ! -d "/home/{{ user }}/.autoenv" ]] && (git clone https://github.com/kennethreitz/autoenv.git "/home/{{ user }}/.autoenv"); } || echo 'pyenv already installed'; \
    echo 'language version managers installed'
  args:
    executable: /bin/bash

- name: Install tools using pip
  shell: . "/home/{{ user }}/.bashrc" && pip install "{{ item }}"
  with_items:
    - credstash
  args:
    executable: /bin/bash

- name: Install python2 version
  shell: . "/home/{{ user }}/.bashrc" && { pyenv versions | grep '2.7.14' || pyenv install 2.7.14; }
  args:
    executable: /bin/bash

- name: Install python3 version
  shell: . "/home/{{ user }}/.bashrc" && { pyenv versions | grep '3.4.4' || pyenv install 3.4.4; }
  args:
    executable: /bin/bash

- name: Set global python version
  shell: . "/home/{{ user }}/.bashrc" && pyenv global 2.7.14 3.4.4
  args:
    executable: /bin/bash

- name: Install ruby version
  shell: . "/home/{{ user }}/.bashrc" && { rbenv versions | grep '2.4.0' || rbenv install 2.4.0; } && rbenv global 2.4.0
  args:
    executable: /bin/bash

- name: Install node version
  shell: . "/home/{{ user }}/.bashrc" && { nvm ls | grep 'v8.9.3' || nvm install 8.9.3; } && nvm alias default 8.9.3
  args:
    executable: /bin/bash

- name: Install golang version
  shell: . "/home/{{ user }}/.bashrc" && { goenv versions | grep '1.9.2' || goenv install 1.9.2; } && goenv global 1.9.2
  args:
    executable: /bin/bash

- name: Install dep the package manager for golang
  shell: . "/home/{{ user }}/.bashrc" && { curl https://raw.githubusercontent.com/golang/dep/master/install.sh | bash; }
  args:
    executable: /bin/bash
