---
# These tasks set up some common binaries needed to work with

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: no
  with_items:
    - curl
    - git
    - libffi-dev
    - libssl-dev
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - build-essential
    - xclip
    - cmake
    - scons
    - autoconf
    - automake
    - autoconf-archive
    - libtool
    - flex
    - bison
    - python-pip
  become: true
  become_user: root

- file: state=directory
    dest=/home/developer/bin
    owner=developer
    group=developer

- file: state=directory
    dest=/home/developer/lib
    owner=developer
    group=developer

- file: state=directory
    dest=/home/developer/golang
    owner=developer
    group=developer

- name: Add extra line to profile file
  shell: echo ". $HOME/.env_vars" >> $HOME/.profile

- name: Add env_vars file to your home dir
  copy: src=env_vars
    dest=/home/developer/.env_vars
    owner=developer
    group=developer
    mode=644
