---
# This task sets up the ssh keys on the machine

- file: path=/home/developer/.ssh/github
        owner=developer
        group=developer
        state=directory

- name: Pushes deploy users github private key to the remote developer users ssh keys
  shell: >
    AWS_ACCESS_KEY_ID={{ aws_access_key_id }} \
    AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }} \
    credstash -r us-west-2 -t kms-cred-stash get -n {{ item.name }} type={{ item.context }} > /home/developer/.ssh/github/{{ item.name }} &&
    chown -R developer:developer /home/developer/.ssh/github/* &&
    chmod 0600 /home/developer/.ssh/github/*
  with_items:
    - name: 'id_rsa'
      context: 'private'
    - name: 'id_rsa.pub'
      context: 'public'

- name: Add github as a known host to the ssh config of developer user
  shell: >
    ssh-keyscan -H github.com >> /home/developer/.ssh/known_hosts && chmod 600 /home/developer/.ssh/known_hosts

- copy: src=config
        dest=/home/developer/.ssh/config
        owner=developer
        group=developer
        mode=600
