---
# These tasks set up various cli tools and utils

- pip: name=maybe
  with_items:
    - maybe
    - doitlive
    - percol
    - supervisor

- name: Setup tldr for bash
  shell: >
    curl -o /home/developer/bin/tldr https://raw.githubusercontent.com/raylee/tldr/master/tldr &&
    chmod +x /home/developer/bin/tldr

- shell: echo 'alias tldr=tldr -p linux' >> /home/developer/.bash_it/custom/aliases.bash

- name: Add inputrc
  copy: src=inputrc
    dest=/home/developer/.inputrc
    owner=developer
    group=developer
    mode=662

- name: Install thefuck
  pip: name=thefuck

# Don't change this to echo a line to an existing file
# Let this be a file in itself
- copy: src=thefuck.bash
    dest=/home/developer/.bash_it/custom/thefuck.bash
    owner=developer
    group=developer
    mode=662
