---
# These tasks set up various cli tools and utils

- name: Install tools using pip
  shell: . "/home/{{ user }}/.bashrc" && pip install --trusted-host pypi.python.org "{{ item }}"
  with_items:
    - maybe
    - percol
    - supervisor
    - csvkit
    - shyaml
    - mycli
    - pgcli
    - cheat
    - docker-compose
    - yq
    - pylint
    - pep8
    - pycodestyle
    - pylama
    - pyflakes
  args:
    executable: /bin/bash

- name: Rehash pyenv for the binaries to be in PATH
  shell: . "/home/{{ user }}/.bashrc" && pyenv rehash
  args:
    executable: /bin/bash

- name: Add inputrc
  copy: src=inputrc
    dest="/home/{{ user }}/.inputrc"
    owner={{ user }}
    group={{ user }}
    mode=662

- name: Install tools using gem
  shell: . "/home/{{ user }}/.bashrc" && gem install "{{ item }}"
  with_items:
    - bundler
    - rake
    - thor
    - fpm
    - pleaserun
    - sqlint
    - mdl
    - rubocop
    - rubocop-rails
    - ruby-lint
  args:
    executable: /bin/bash

- name: Rehash rbenv for the binaries to be in PATH
  shell: . "/home/{{ user }}/.bashrc" && rbenv rehash
  args:
    executable: /bin/bash

- name: Install wiremock
  shell: >
    . "/home/{{ user }}/.bashrc" &&
    cd "/home/{{ user }}/lib" &&
    wget http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/2.9.0/wiremock-2.9.0.jar &&
    mv wiremock-2.9.0.jar wiremock.jar
  args:
    executable: /bin/bash

- name: Install tflint
  shell: >
    . "/home/{{ user }}/.bashrc" &&
    cd "/home/{{ user }}/tmp" &&
    wget https://github.com/wata727/tflint/releases/download/v0.7.0/tflint_linux_amd64.zip &&
    unzip tflint_linux_amd64.zip &&
    install tflint "/home/{{ user }}/bin"
  args:
    executable: /bin/bash

- name: Install npm utilities
  shell: . "/home/{{ user }}/.bashrc" && npm install -g "{{ item }}"
  with_items:
    - how2
    - cpy-cli
    - strip-json-comments-cli
    - doctoc
    - git-commander
    - gistup
    - pretty-bytes-cli
    - normalize-newline-cli
    - speed-test
    - json2csv
    - xml2json-command
    - json2yaml
    - localtunnel
    - strip-css-comments-cli
    - weather-cli
    - trash-cli
    - empty-trash-cli
    - js-beautify
    - jsonlint
    - jshint
    - js-yaml
  args:
    executable: /bin/bash

- name: Install tools using golang
  shell: . "/home/{{ user }}/.bashrc" && go get -u "{{ item }}"
  with_items:
    - github.com/jteeuwen/go-bindata/...
    - github.com/tylertreat/comcast
    - github.com/derekparker/delve/cmd/dlv
    - github.com/fatih/hclfmt
    - github.com/mitchellh/gox
    - mvdan.cc/interfacer
    - github.com/jgautheron/goconst/cmd/goconst
    - github.com/opennota/check/cmd/aligncheck
    - github.com/opennota/check/cmd/structcheck
    - github.com/opennota/check/cmd/varcheck
    - github.com/mdempsky/maligned
    - mvdan.cc/unparam
    - github.com/stripe/safesql
    - github.com/alexkohler/nakedret
    - honnef.co/go/tools/cmd/unused
    - github.com/alecthomas/gometalinter
  args:
    executable: /bin/bash

- name: Add an alias for rm
  shell: >
    . "/home/{{ user }}/.bashrc" &&
    echo 'alias rm=trash' >> "/home/{{ user }}/.bash_it/custom/aliases.bash"
  args:
    executable: /bin/bash

- copy: src=agignore dest="/home/{{ user }}/.agignore" owner={{ user }} group={{ user }} mode=600

- copy: src=tigrc dest="/home/{{ user }}/.tigrc" owner={{ user }} group={{ user }} mode=600

- name: Add universal ctags
  shell: >
    { ctags_install_dir="$(mktemp -d "/tmp/ctags.XXXX")"; } &&
    cd "$ctags_install_dir" &&
    git clone https://github.com/universal-ctags/ctags.git &&
    cd ctags &&
    ./autogen.sh &&
    ./configure &&
    make &&
    make install &&
    cd ~ &&
    rm -rf "$ctags_install_dir"
  args:
    executable: /bin/bash
  become: true
  become_user: root

- copy: src=ctags dest="/home/{{ user }}/.ctags" owner={{ user }} group={{ user }} mode=600

- name: Add package info to sources for sysdig
  shell: >
    curl -s https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public | apt-key add - &&
    curl -s -o /etc/apt/sources.list.d/draios.list http://download.draios.com/stable/deb/draios.list
  args:
    executable: /bin/bash
  become: true
  become_user: root

- apt:
    update_cache: yes
  become: true
  become_user: root

- apt:
    name: "{{ item }}"
    state: present
    force: yes
    install_recommends: no
  with_items: "{{ apt.utils }}"
  become: true
  become_user: root

- name: Install concurrent multi server mysql client
  shell: . "/home/{{ user }}/.bashrc" && /bin/bash -ic "cd /home/{{ user }}/bin && curl -sSL -0 https://github.com/github/ccql/releases/download/v1.1.4/ccql-binary-linux-20160316084430.tar.gz | tar xz"
  args:
    executable: /bin/bash

- name: Install terraform
  shell: >
    . "/home/{{ user }}/.bashrc" &&
    cd "/home/{{ user }}/tmp" &&
    wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip &&
    unzip terraform_0.11.7_linux_amd64.zip &&
    install terraform /home/{{ user }}/bin
  args:
    executable: /bin/bash

- name: Enable completions for bashit
  shell: . "/home/{{ user }}/.bashrc" && /bin/bash -ic "bash-it enable {{ ' '.join(bash_it.completions) }}"
  args:
    executable: /bin/bash

- name: Enable plugins for bashit
  shell: . "/home/{{ user }}/.bashrc" && /bin/bash -ic "bash-it enable plugin {{ ' '.join(bash_it.plugins) }}"
  args:
    executable: /bin/bash

- name: Enable aliases for bashit
  shell: . "/home/{{ user }}/.bashrc" && /bin/bash -ic "bash-it enable alias {{ ' '.join(bash_it.aliases) }}"
  args:
    executable: /bin/bash
