---
# These tasks set up various cli tools and utils

- name: Install Linuxbrew util packages
  shell: /bin/bash -ic "brew install {{ ' '.join(homebrew.utils) }}"

- name: Install tools using pip
  shell: /bin/bash -ic "pip install {{ item }}"
  with_items:
    - maybe
    - doitlive
    - percol
    - supervisor
    - csvkit
    - shyaml
    - credstash

- name: Setup tldr for bash
  shell: >
    curl -o /home/developer/bin/tldr https://raw.githubusercontent.com/raylee/tldr/master/tldr &&
    chmod +x /home/developer/bin/tldr

- name: Add inputrc
  copy: src=inputrc
    dest=/home/developer/.inputrc
    owner=developer
    group=developer
    mode=662

- apt_repository:
    repo: 'ppa:russell-s-stewart/ppa'
    state: present
  become: true
  become_user: root

- apt: update_cache=yes
  become: true
  become_user: root

- name: Install sshrc
  apt:
    name: sshrc
    state: present
    update_cache: yes
    install_recommends: no
  become: true
  become_user: root

- name: Install tools using gem
  shell: /bin/bash -ic "gem install {{ item }}"
  with_items:
    - bundler
    - rake
    - thor
    - fpm
    - pleaserun

- name: Install wiremock
  shell: >
    cd /home/developer/lib &&
    wget http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock/1.57/wiremock-1.57-standalone.jar &&
    mv wiremock-1.57-standalone.jar wiremock.jar

- file: state=directory
    dest=/home/developer/.tldr
    owner=developer
    group=developer

- name: Install npm utilities
  shell: /bin/bash -ic "npm install -g {{ item }}"
  with_items:
    - how2
    - cpy-cli
    - trash-cli
    - empty-trash-cli
    - strip-json-comments-cli
    - doctoc
    - git-commander
    - gistup
    - pretty-bytes-cli
    - normalize-newline-cli
    - speed-test
    - weather-cli
    - strip-css-comments-cli
    - localtunnel
    - json2csv
    - xml2json-command

- name: Add an alias for rm
  shell: >
    echo 'alias rm=trash' >> /home/developer/.bash_it/custom/aliases.bash
  sudo: no

- copy: src=agignore dest=/home/developer/.agignore owner=developer group=developer mode=600

- name: Add package info to sources for sysdig
  shell: >
    curl -s https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public | apt-key add - &&
    curl -s -o /etc/apt/sources.list.d/draios.list http://download.draios.com/stable/deb/draios.list
  become: true
  become_user: root

- apt:
    update_cache: yes
  become: true
  become_user: root

- apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt.utils }}"
  become: true
  become_user: root

- name: Install go utilities
  shell: /bin/bash -ic "go get -u '{{ item }}'"
  with_items:
    - github.com/rakyll/boom
    - github.com/tsenart/vegeta
    - github.com/msoap/shell2http
    - github.com/cortesi/modd/cmd/modd
    - github.com/jteeuwen/go-bindata/...
    # - github.com/quii/mockingjay-server
    - github.com/tylertreat/comcast
    # - github.com/buger/gor

- name: Install concurrent multi server mysql client
  shell: /bin/bash -ic "cd $HOME/bin && curl -s -S -L -0 https://github.com/github/ccql/releases/download/v1.1.4/ccql-binary-linux-20160316084430.tar.gz | tar xz"

- name: Enable completions for bashit
  shell: /bin/bash -ic "bash-it enable {{ ' '.join(bash_it.completions) }}"

- name: Enable plugins for bashit
  shell: /bin/bash -ic "bash-it enable plugin {{ ' '.join(bash_it.plugins) }}"

- name: Enable aliases for bashit
  shell: /bin/bash -ic "bash-it enable alias {{ ' '.join(bash_it.aliases) }}"
