---
# These tasks set up various cli tools and utils

- name: Install go
  shell: >
    cd /opt &&
    wget https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz &&
    tar -C /usr/local -xzf go1.6.2.linux-amd64.tar.gz &&
    rm go1.6.2.linux-amd64.tar.gz

- name: Add go bin to PATH
  shell: echo 'export PATH=/usr/local/go/bin:$PATH' >> /home/developer/.bash_it/custom/utils.bash
  sudo: no

- name: Add go path to bash_profile
  shell: >
    echo 'export GOPATH=$HOME/golang' >> /home/developer/.bash_it/custom/utils.bash
    echo 'export PATH=$GOPATH/bin:$PATH' >> /home/developer/.bash_it/custom/utils.bash
  sudo: no
