---
# These tasks set up tmux for development machine

- shell: . "/home/{{ user }}/.bashrc" && curl -s -S -L https://raw.githubusercontent.com/sumanmukherjee03/tmux_setup/master/bootstrap.sh | bash -i
  args:
    executable: /bin/bash

- file: path="/home/{{ user }}/.projects.json"
        owner={{ user }}
        group={{ user }}
        state=touch
