---
# These tasks set up node

- name: Add node PPA
  shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

- apt: update_cache=yes
  become: true
  become_user: root

- name: Install node
  apt: name=nodejs
  become: true
  become_user: root
