---
# These tasks install vim

- name: Install vim
  shell: /bin/bash -ic "brew install vim {{ ' '.join(vim.config_options) }}"
  register: is_vim_installed

- name: Install vim config
  shell: >
    curl -s -S -L https://raw.githubusercontent.com/sumanmukherjee03/vim_setup/master/bootstrap.sh | bash &&
    cd /home/developer/.vim &&
    make
  when: is_vim_installed|success
