---
# These tasks install docker and its dependencies

- name: install-apt-packages-for-docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: no
  with_items:
    - apt-transport-https
    - ca-certificates
  become: true
  become_user: root

- shell: apt-get install -yq "linux-headers-$(uname -r)" linux-image-extra-virtual
  become: true
  become_user: root

- name: install-docker-on-host
  apt:
    name: docker
    state: present
    install_recommends: yes
    update_cache: yes
  become: true
  become_user: root
  register: is_docker_installed

- pip:
    name: docker-compose
  become: true
  become_user: root
