---
# These tasks install docker and its dependencies

- name: install-apt-packages-for-docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: no
  with_items:
    - apt-transport-https
    - ca-certificates
  become: true
  become_user: root

- shell: apt-get install -yq "linux-headers-$(uname -r)" linux-image-extra-virtual
  become: true
  become_user: root

- name: install-docker-on-host
  apt:
    name: 'docker.io'
    state: present
    install_recommends: yes
    update_cache: yes
  become: true
  become_user: root
  register: is_docker_installed

- name: install-docker-machine
  shell: >
    base=https://github.com/docker/machine/releases/download/v0.14.0 &&
    curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
    install /tmp/docker-machine /usr/local/bin/docker-machine
  become: true
  become_user: root
  register: is_docker_machine_installed

- pip:
    name: docker-compose
  become: true
  become_user: root
