---
# This playbook deploys the workstation

- hosts: all
  become: true
  become_user: "{{ user }}"
  become_method: sudo
  gather_facts: true
  environment:
    HOME: "/home/{{ user }}"
  roles:
    - common

- hosts: workstation
  become: true
  become_user: "{{ user }}"
  become_method: sudo
  gather_facts: true
  roles:
    - ssh
    - git
    - bash-it
    - vim
    - tmux
    - utils
    - docker
    - docker-machine
    - minikube
    - mysql
    - postgres
