---
# This playbook provisions servers with some opinionated basic stuff
# It adds some extras if it is a workstation

- hosts: all
  become: true
  become_user: "{{ user }}"
  become_method: sudo
  gather_facts: true
  environment:
    HOME: "/home/{{ user }}"
  roles:
    - common
    - ssh
    - git
    - bash-it
    - vim
    - tmux
    - utils
    - docker
    - mysql
    - postgres

- hosts: workstation
  become: true
  become_user: "{{ user }}"
  become_method: sudo
  environment:
    HOME: "/home/{{ user }}"
  gather_facts: true
  roles:
    - role: virtualbox
      when: playbook_type != 'CLOUD_VM'
    - role: docker-machine
      when: playbook_type != 'CLOUD_VM'
    - role: minikube
      when: playbook_type != 'CLOUD_VM'
    - role: minishift
      when: playbook_type != 'CLOUD_VM'
